name: Check Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  check_security:
    name: Build and Test
    runs-on: ubuntu-22.04 # ubuntu-latest | waiting for PR acceptance

    strategy:
      matrix:
        elixir: ['1.16.0']
        otp: ['26.0']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}

      - name: Restore dependencies cache
        id: cache
        uses: actions/cache@v3
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-

      # - name: Install dependencies
      #   if: steps.cache.outputs.cache-hit != 'true'
      #   run: mix deps.get

      - name: Install Mix Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          mix local.rebar --force 
          mix local.hex --force 
          mix local.hex --force 
          mix deps.get
          mix ecto.create

      - name: Check coverage and tests
        run: mix coveralls.html 

    services:
      pg:
        image: postgres:12 
        ports: ['5432:5432'] 
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
            --health-cmd pg_isready 
            --health-interval 10s 
            --health-timeout 5s 
            --health-retries 5